### PR TITLE
the reported need the results from run

### PR DESCRIPTION
**Pull request by eisisig**

### CODE REVIEW

**Comment by deepsweet** [comment]
hi. I have not used and not tested this task by myself for a while, so thanks for the fix. could you please fix some codestyle errors? see details from Travis build. or [allow me](https://github.com/blog/2247-improving-collaboration-with-forks) to do this.

**Comment by eisisig** [comment]
Just lazy of me not running the linter before committing, sorry for that... 👎 
So I fixed it and re-pushed 👍 

I will monitor the build tests

**Comment by deepsweet** [comment]
also do we need to fix the same [here](https://github.com/eisisig/ava/blob/3a3940e7b7391f770fa85a445df863789f7fdb80/lib/index.js#L56-L57)?

**Comment by deepsweet** [comment]
👍  thanks

**Pull request merged**
